### PR TITLE
altered the region graph on the dashboard to display percentages with respect to total time

### PR DESCRIPTION
**Pull request by branden14k**
altered the region graph on the dashboard to display percentages of time
for awake, active and rest in proportion to total time. Also centered
the dashboard layout as it was not centered anymore.

### CODE REVIEW

**Comment by branden14k** [comment]
please take a look.

**Comment by BenTheElder** [comment]
This looks pretty nice!
The fields still say "mins" however instead of percentage, and the whole page now has a 7% left side. It doesn't look centered to me? I'll pm a screenshot.

**Comment by branden14k** [comment]
just an fyi, the thing where the graphs say minutes was fixed. take a look and let me know if we can merge

**Comment by BenTheElder** [comment]
The code doesn't appear to have changed since the 28th, so my previous comments still stand. At minimum I think we ought to use the same width for all tab content divs.
 
Maybe get a review from someone on front-end before merging: @ChelsiAlise  @jedmpaz @william7hsu

**Comment by branden14k** [comment]
i pushed the change right before your comment as chelsi pointed it out in slack. the change is there. it was committed check the commit history.

**Comment by branden14k** [comment]
@ChelsiAlise @william7hsu @jedmpaz does my branch interfere with what you guys are working on? looking to merge this

**Comment by BenTheElder** [comment]
screenshot from 2017-03-05 18-34-20

https://github.com/ChelsiAlise/workingdogdatadash/pull/80/files#r103581449

**Comment by branden14k** [comment]
also going back to the width on cent divs, do you guys want to center the content or leave as is?

**Comment by branden14k** [comment]
@BenTheElder the final commit. look at what was changed. it was removing the mins and putting percentage. the commit that says "correcting the issue" it is literally one thing of the two things changed in that commit

**Comment by branden14k** [comment]
screen shot 2017-03-05 at 6 42 53 pm @BenTheElder

**Comment by BenTheElder** [comment]
If you look through the comments above you can see that my comments are about other things, like the content div styling. I'm aware of your commit and my remaining comments were made after it, 5 days ago.
Here is another direct link to one of them:
https://github.com/ChelsiAlise/workingdogdatadash/pull/80/files#r103581579

Please check the "files changed" tab if you cannot see them above:
screenshot from 2017-03-05 18-48-38

**Comment by branden14k** [comment]
okay, i thought you were still referring to the graph itself.  Apologies. so if 10% is too high what are your ideas for padding. I know we have to consider platforms of smaller screens, but i do think the padding looks nice. maybe a smaller padding? @BenTheElder

**Comment by BenTheElder** [comment]
I just wanted to point out that the new padding is only applied to the dashboard tab and that on mobile you get something like this:

screenshot from 2017-03-05 19-03-11

Perhaps we could use a media-query that targets a minimum screen-size. That would allow larger padding when possible, while falling back to something smaller (and probably fixed size) in smaller render contexts.

Personally I'm reasonably happy with the dashboard portion as-is, but I think you should discuss what to do with the rest of the team and decide with them. Maybe if they don't get back to you soon you can make those changes in a different pull request and finish this one out.

**Comment by branden14k** [comment]
@ChelsiAlise @william7hsu @jedmpaz take a look and let me know if i can merge this branch or not

**Pull request merged**
