### PR TITLE
Fix zoom reset on dashboard

### PR DESCRIPTION
**Pull request by branden14k**
Fix zoom reset button placement on dashboard graphs so the button no longer blocks the legend.

### CODE REVIEW

**Comment by BenTheElder** [comment]
The reset zoom layout appears to be set the same for all of the graphs, can that be set [here (index.js line ~28)](https://github.com/ChelsiAlise/workingdogdatadash/blob/master/static/index.js#L28)?

**Comment by branden14k** [comment]
yeah i can try that!

**Comment by branden14k** [comment]
better? @BenTheElder

**Comment by BenTheElder** [comment]
LGTM 👍

**Comment by BenTheElder** [comment]
This tentatively closes #60

**Pull request merged**
