### PR TITLE
Added chart for averages per region to the dashboard.

### PR DESCRIPTION
**Pull request by branden14k**
Added chart for averages per region to the dashboard.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Tentatively LGTM, I'd like to pull and run it before merging though so we don't get a repeat of #66 / #67.

**Comment by BenTheElder** [comment]
This needs to be tagged with the sprint it's going under, (2/3?)

**Comment by BenTheElder** [comment]
Some comments:
 - the units should be changed to percentage or average by day, using total minutes skews the comparisons by the amount of data per dog

Otherwise this looks pretty nice. 👍

**Comment by branden14k** [comment]
well the graph right above it uses totals, and i thought the averaging of the data would negate skewing affect. as each region is subject to the same variations within the data

**Comment by BenTheElder** [comment]
Aome of the average totals are above 1 day, that means they're based on the amount of data we have instead of the average amount of rest, sleep, etc. the dogs are getting.

**Comment by BenTheElder** [comment]
The graph above it was mostly left alone from the old dashboard from #10.

screenshot from 2017-02-18 23-18-22

There are 1400 minutes in a day, yet North Central has a Rest average of 458,755 minutes. That _has_ to be wrong or influenced by the amount of recorded minutes in that region rather than dogs actually getting the most rest in that region.
What we really want is the average amount of time on any given day spent resting, or the average percentage of a recorded day spent resting. Not the average of the dogs's totals over some arbitrary period of time.

**Pull request closed without merging**
