### PR TITLE
Add points data analysis

### PR DESCRIPTION
**Pull request by BenTheElder**
This adds an ipython notebook to analyze the points data set.

### CODE REVIEW

**Comment by BenTheElder** [comment]
This depends on #78.

**Comment by BenTheElder** [comment]
This is not done yet. DO NOT MERGE!

**Comment by jedmpaz** [comment]
So I gave the new graph stuff a look since my own stuff wasn't getting me anywhere, and I got this: 
screen shot 2017-02-26 at 2 40 27 pm

**Comment by BenTheElder** [comment]
I'm pulling this back up on my machine, I'll check this.

**Comment by BenTheElder** [comment]
@jedmpaz I'll push a fix once it's done computing but for now you can `s/colors/color` on the line:
`plot_series = {outcome:[list(), list(), list()] for outcome in colors}`
IE to:
`plot_series = {outcome:[list(), list(), list()] for outcome in color}`

**Comment by BenTheElder** [comment]
Closing this, this doesn't need to be added to git anyhow, the other file should serve as enough example.

**Pull request closed without merging**
