### PR TITLE
route customChart.html in the dev server for now

### PR DESCRIPTION
**Pull request by BenTheElder**
this takes care of #43

### CODE REVIEW

**Comment by BenTheElder** [comment]
Will merge after a review, this allows loading customChart.html as expected when using `dev_server.py`.

**Comment by ChelsiAlise** [comment]
What does this do/improve?

**Comment by BenTheElder** [comment]
If you run dev server and click the custom chart button without this change
it does not work because we are serving it at /customChart.html specially
on the production server.

**Comment by BenTheElder** [comment]
If you look at the single 3 line change it might be clearer. Basically it maps queries for /customChart.html to /static/customChart.html to mimic the server we actually have deployed.

**Pull request merged**
