### PR TITLE
add outcome data fields to server and upload script

### PR DESCRIPTION
**Pull request by BenTheElder**
this is part of completing #18

### CODE REVIEW

**Comment by BenTheElder** [comment]
After merging this I can actually refresh the server data, and the new fields will be added to the dog objects.

**Comment by ChelsiAlise** [comment]
sounds good as long as it doesn't affect the structure of the json and affect how we are parsing through the json on the front end

**Comment by BenTheElder** [comment]
It adds new fields to the dogs' objects (see the code comments in the
changeset for which fields). If that somehow breaks the parsing then the
parsing is wrong and should be fixed.

On Jan 27, 2017 02:30, "ChelsiAlise" <notifications@github.com> wrote:

sounds good as long as it doesn't affect the structure of the json and
affect how we are parsing through the json on the front end

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ChelsiAlise/workingdogdatadash/pull/45#issuecomment-275605382>,
or mute the thread

**Comment by BenTheElder** [comment]
Thanks, will merge and then deploy.

**Pull request merged**
